# Generated by Django 4.2.5 on 2024-02-11 17:49

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_add_indexes_change_fild_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personfilmwork',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='creation_date',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now()),
        ),
    ]
